// Types generated by prost-build from proto/*.proto.
// All messages live in the evanescent.v1 proto package.
// Many types are used only by the Android client or by not-yet-implemented features.
#![allow(dead_code)]
include!(concat!(env!("OUT_DIR"), "/evanescent.v1.rs"));
